<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAKmPwmQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAKmPwmQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAKmPwmQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAKmPwmQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAKmPwmQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'AKmPwmQ',
    'container.build_id' => '187a8dd3',
    'container.build_time' => 1712043675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAKmPwmQ');
