<?php

namespace ContainerAKmPwmQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P1KYQUuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p1KYQUu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p1KYQUu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.p1KYQUu.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.p1KYQUu": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".'],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
        ], [
            'order' => 'App\\Entity\\Order',
            'orderRepository' => 'App\\Repository\\OrderRepository',
        ]);
    }
}
