<?php

namespace ContainerAKmPwmQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7bSenCkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7bSenCk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7bSenCk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'positionRepository' => ['privates', 'App\\Repository\\PositionRepository', 'getPositionRepositoryService', true],
        ], [
            'positionRepository' => 'App\\Repository\\PositionRepository',
        ]);
    }
}
