<?php

namespace ContainerAKmPwmQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..f4rJwr.App\Entity\Contact' shared service.
     *
     * @return \App\Entity\Contact
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..f4rJwr": it needs an instance of "App\\Entity\\Contact" but this type has been excluded in "config/services.yaml".');
    }
}
