<?php

namespace ContainerAKmPwmQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderDetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.46sBBwb.App\Entity\OrderDetail' shared service.
     *
     * @return \App\Entity\OrderDetail
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.46sBBwb": it needs an instance of "App\\Entity\\OrderDetail" but this type has been excluded in "config/services.yaml".');
    }
}
