<?php

namespace ContainerAKmPwmQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPositionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5eDsfgt.App\Entity\Position' shared service.
     *
     * @return \App\Entity\Position
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5eDsfgt": it needs an instance of "App\\Entity\\Position" but this type has been excluded in "config/services.yaml".');
    }
}
